### ISSUE TITLE
Support build on multiple bases in our charms

### ISSUE THREAD

**Issue by rgildein** [canonical/solutions-engineering-automation#114]
We need to start using build-on with multiple bases, so instead of building on one base and define runs on multiple.
E.g.
```yaml
- build-on:
    - name: ubuntu
      channel: "22.04"
      architectures: ["arm64"]
    run-on:
      - name: ubuntu
        channel: "24.04"
        architectures:
          - arm64
      - name: ubuntu
        channel: "22.04"
        architectures:
          - arm64
      - name: ubuntu
        channel: "20.04"
        architectures:
          - arm64
```
should be defined like this
```yaml
- build-on:
    - name: ubuntu
      channel: "24.04"
      architectures: ["arm64"]
    run-on:
      - name: ubuntu
        channel: "24.04"
        architectures:
          - arm64

- build-on:
    - name: ubuntu
      channel: "22.04"
      architectures: ["arm64"]
    run-on:
      - name: ubuntu
        channel: "22.04"
        architectures:
          - arm64

- build-on:
    - name: ubuntu
      channel: "20.04"
      architectures: ["arm64"]
    run-on:
      - name: ubuntu
        channel: "20.04"
        architectures:
          - arm64
```
This is related to multiple charms and we need to define which will be effected.

# Acceptance Criteria
- Defined list of charms, which needs to support it
- Align our functional test to be able to run with proper charm file, since charmcraft pack will be produce multiple charm files.
- Align our release to be able to release multiple charm files.
