### ISSUE TITLE
Weekly test should be able to dispatch workflow with arguments

### ISSUE THREAD

**Issue by rgildein** [canonical/solutions-engineering-automation#9]
There are some repos which will benefit from dispatching workflow with arguments.

For example, the [charm-prometheus-juju-exporter](https://github.com/canonical/charm-prometheus-juju-exporter) could benefit from it and the weekly test could run multiple times for each juju-channel. This was discussed internally, and we decide to drop juju-channel 3.1, 3.2 and 3.3 from [#52](https://github.com/canonical/charm-prometheus-juju-exporter/pull/52) due to stability (lot of times one will fail) and time expense of such run. 

Example:
```yaml
         - repo: charm-prometheus-juju-exporter
            workflow_file_name: check.yaml
            branch: main
            arguments: 
              juju-channel: '3.1/stable'
         - repo: charm-prometheus-juju-exporter
            workflow_file_name: check.yaml
            branch: main
            arguments: 
              juju-channel: '3.2/stable'
...
```
